### ISSUE TITLE
UNIT_PERCENTAGE was changed to PERCENTAGE in 0.115 upgrade

### ISSUE THREAD

**Issue by sparky14** [marthoc/homeseer#10]
UNIT_PERCENTAGE was changed to PERCENTAGE in 0.115.  Any entities displaying % in Custom Component/Integrations will now error.

**Comment by kmitch95120** [comment]
Working on a fix.

**Comment by kmitch95120** [comment]
Per a recommendation from the Development sub-group, I've defined UNIT_PERCENTAGE locally instead of importing it from homassistant.const.
