### ISSUE TITLE
Filter Event

### ISSUE THREAD

**Issue by Darnshelm** [marthoc/homeseer#12]
Hi i wounder if it possible to filter some events I don't need all events?
Ha says it only allowing 150 units?
or it possible to change this?

**Comment by marthoc** [comment]
Unfortunately at the moment it is all-or-nothing, there is no way to filter which events get imported in the custom component presently. I'm going to leave this issue open and it's possible I might add it in the future. EDIT: I just had a look at the HomeSeer API documentation - one way to filter might be by allowing you to specify which event groups get imported in configuration.yaml.

**Comment by Darnshelm** [comment]
I think that will be possible then i will be very simple to make a HA event group to select what to import.
I have also imported arduino And rfxcom unit with you plugin in home assistant. just changing Device Type (String) name to what corresponding unit in z-wave.
and it works great

**Comment by marthoc** [comment]
@Darnshelm Can you test some new code for me? I've added a new configuration key that will allow you to specify which event groups get imported into HA as scenes.

You'll need to switch the GitHub branch to test the code. Stop Home Assistant, then from inside your custom_components/homeseer directory, do:
```
git fetch
git pull
git checkout allowed-event-groups
```
Then start and stop Home Assistant to make sure the new code gets loaded.

To test, add the key `allowed_event_groups`, which is a list of event group names that you want imported to your configuration.yaml as follows:
```
homeseer:
  allowed_event_groups: [ "Sample Event Group 1", "Sample Event Group 2" ]
```
or
```
homeseer:
  allowed_event_groups:
    - "Sample Event Group 1"
    - "Sample Event Group 2"
```
When you restart, only the events from the event groups you specify should get loaded.

**Comment by Darnshelm** [comment]
Hi
Yes i can test this tomorrow and see how it works.
Thx  for adding this code.


Den fre 11 dec. 2020 17:02Mark Coombes <notifications@github.com> skrev:

**Comment by Darnshelm** [comment]
Hi
I try you code and it works only events in that event group are addet to HA
Have try to run the event also from HA that also works great.
Something more you want me to try?

I don't have any Z-wave device in my system. so to get your plugin to
export my devices to HA I change Device type sting from (Arduino output) to
Z-wave switch
are that possible general device option just like say HA switch or HA switch

Problem I have on my arduino Output (swtich). the relayboard that the
output are connect works inverted. but in homeseer I have options  invert
on/off function when i make new device output
i wounder what kind of data values are HA reading from homeseer to get
device status? if it on or off or dim
does it read device status or device value. so i know make a change in yaml
file what value to invert to


//David


Den fre 11 dec. 2020 kl 20:06 skrev David Arnshelm <darnshelm@gmail.com>:
