### ISSUE TITLE
Multiple Z-Wave locks only first one works

### ISSUE THREAD

**Issue by lowgatelabs** [marthoc/homeseer#13]
I have 3 Schlage Z-Wave locks (all same model) which the homeseer integration successfully created in Home assistant as:

lock.door_lock
lock.door_lock_2
lock.door_lock_3

The third lock works fine and I can lock/unlock from Home Assistant, and the status updates correctly in the UI and appropriate messages appear in the Homeseer log. The other two (lock.door_lock and lock.door_lock2) do not update status, nor do they appear to contact homeseer when their lock/unlock button is pressed in the UI. The lock history also does not update when the lock status is changed in homeseer.

When I click the "Lock" toggle in the home assistant UI, I get the following in the Home Assistant log:

`2020-11-11 13:55:00 ERROR (MainThread) [pyhs3.const] HomeSeer HTTP Request error: Invalid variable type: value should be str or int, got None of type <class 'NoneType'>
2020-11-11 13:55:13 ERROR (MainThread) [pyhs3.const] HomeSeer HTTP Request error: Invalid variable type: value should be str or int, got None of type <class 'NoneType'>`

There are no messages in the Homeseer log.

**Comment by marthoc** [comment]
Can you set debug logging for both pyhs3 and homeseer and then try to toggle the locks? Need to see what’s happening under the hood.

**Comment by lowgatelabs** [comment]
I've posted the logs to the Home Assistant thread here: https://community.home-assistant.io/t/hello-from-a-homeseer-hs4-refugee/181820/295

It does indeed appear that there's an error occurring is pyhs3 before communication is even attempted to from HA to HS3.

What's strange is that all locks are the same make/model. The only thing I can think of is that in the case of multiple locks, when the devices are created in HA something is getting incremented too early and that borks the configuration of all locks except the last one created. This is complete speculation on my part as I'm not smart enough to understand python.

**Comment by marthoc** [comment]
This should now be fixed in the latest version of the custom component (0.7) - I've posted an explanation in the Home Assistant community here: https://community.home-assistant.io/t/hello-from-a-homeseer-hs4-refugee/181820/302?u=marthocoo. Please delete the current homeseer directory and reinstall and all should work!
