### ISSUE TITLE
Temperatur and lux not showing in HA

### ISSUE THREAD

**Issue by steinis123** [marthoc/homeseer#16]
I have multiple fibaro motion sensors and battery and motion is working just fine. But the temp and lux sensors are not visible in HA. How can I fix this?:)

**Comment by marthoc** [comment]
@steinis123 Your testing would be appreciated so that I can merge and release. Thanks!

**Comment by steinis123** [comment]
Have been testing it for a couple of days now and it seems to be working very good.

**Comment by marthoc** [comment]
@steinis123 Great, thanks for letting me know. Can you confirm that the correct units of measure are displayed in Home Assistant?

**Comment by steinis123** [comment]
Yes both value and unit seems right. 
![image](https://user-images.githubusercontent.com/28383488/102464875-3a515400-404d-11eb-83f5-c0a9bf3fd16c.png)
