### ISSUE TITLE
Work in HS4? 

### ISSUE THREAD

**Issue by marc-gist** [marthoc/homeseer#18]
Will this work with HS4?

Do you have plans to integrate with the new websocket?

Thanks!

**Comment by kmitch95120** [comment]
Yes, this works with HS4.  The component uses pyhs3 to interact with the HS ASCII and JSON interfaces.  The downside to using the webhook method is that it's only in HS4.  Also, only one webhook can be defined at a time, so only one application can use it. In other words, you can't use this component and Node-RED at the same time to talk to HS4.

**Comment by marthoc** [comment]
Confirming that this integration works with HS4. No plans to update to use the websocket for the reasons @kmitch95120 indicated. ASCII works very well!
