### ISSUE TITLE
Z-Wave Door Lock Logging

### ISSUE THREAD

**Issue by danielbrunt57** [marthoc/homeseer#24]
![image](https://user-images.githubusercontent.com/49846893/106327268-a1f4e480-6232-11eb-8948-b9367b59ab57.png)

I can edit the HS _Device Type String_ if need be.

I've moved my Vision door lock from HA back to HS since ozw cannot properly handle the logging records.  Somehow it's current record is always one record behind the actual current record.  Max stored records on the lock is 50 but since it last hit 50, the new current record is `invalid record`.  I excluded it from ozw, added it to HS and the log record is okay now.  No idea what ozw is doing!!!

Anyway, I had a sensor in HA from which I parsed the segments and converted the lock's UTC time to local time.  It would be nice to have that back again!

![image](https://user-images.githubusercontent.com/49846893/106327593-42e39f80-6233-11eb-83e9-d0fefa0a33f6.png)

```
#   Door Locks
      frontdoor_lock_log_date:
        friendly_name: "Frontdoor Lock Log"
        value_template: '{{ states.sensor.front_door_lock_logging.attributes["TimeStamp"] | timestamp_custom("%d/%m/%y %H:%M:%S") }}'
      
      frontdoor_lock_log_message:
        friendly_name: "Frontdoor Lock Log"
        value_template: '{{ states.sensor.front_door_lock_logging.attributes["Value"].split("\t")[1].split(":")[1].strip() }}'

      frontdoor_lock_log_user:
        friendly_name: "Frontdoor Lock Log"
        value_template: '{{ states.sensor.front_door_lock_logging.attributes["Value"].split("\t")[2].split(":")[1].strip() }}'

      frontdoor_lock_log_code:
        friendly_name: "Frontdoor Lock Log"
        value_template: '{{ states.sensor.front_door_lock_logging.attributes["Value"].split("\t")[3].split(":")[1].strip() }}'
```

**Comment by danielbrunt57** [comment]
I've changed the HS device type string to Z-Wave Operating State but it shows like this:
![image](https://user-images.githubusercontent.com/49846893/106344625-b56a7480-625f-11eb-93e4-d6f67cc87698.png)
and the status is wrong:
![image](https://user-images.githubusercontent.com/49846893/106344639-cfa45280-625f-11eb-87c6-64bf15fe8485.png)

Hopefully, you can find a way to create HA sensors from HS devices which have text based strings as their status.

It would also be nice to be able to add an _integration defined_ device type string to HS Virtual devices so that the integration will create them as helper entities in HA since in HS you can type in whatever you want.  I've used Z-Wave Switch Binary to force the issue and it creates an HA switch.  Since HS does not assign anything to virtuals, you are at liberty to dream up a naming convention... _Homeseer Input Boolean_?  _Virtual Boolean_?

I can see this integration gaining ground over the mcsMQTT method which is quite complex for most users!

Next will be a way to add the integration via HACS.  Then a config flow for it!  And a way to reload it without having to restart HA!

**Comment by marthoc** [comment]
As a workaround for now you should be able to set the device type string to “Z-Wave Sensor Multilevel”, which should give you a text-string sensor. 

You are right that it would be useful to have an arbitrary string for virtual devices in HS. 

I’m actually working on the config flow for the integration now and this will allow you to load and unload without restarting HA. I do have another custom component in HACS format though personally prefer to update via git.

**Comment by danielbrunt57** [comment]
After changing the string in HS...

![image](https://user-images.githubusercontent.com/49846893/106369450-4b58da80-6306-11eb-8e40-8f3f669e6c39.png)

and restarting HA I was able to remove the old entity but the new one is not showing up...

![image](https://user-images.githubusercontent.com/49846893/106369439-27959480-6306-11eb-8280-8e2e907b6f80.png)

I've restarted HA a couple of times.
Pointers on how to troubleshoot?

**Comment by marthoc** [comment]
Hmm I forgot about the fact that in HomeSeer values are integer and status is text. I think the way to handle this is to support a few virtual devices, for example:

HA Switch (for HS virtual devices with on/off)
HA Sensor (for HS devices where you want the numeric status in HA)
HA Status Sensor (for HS devices where you want the status string in HA)

**Comment by danielbrunt57** [comment]
Thanks!

I reviewed HA logs before reading your last post...

![image](https://user-images.githubusercontent.com/49846893/106374308-f4b7c480-6336-11eb-80ad-0314f09dadb8.png)

**Comment by marthoc** [comment]
@danielbrunt57 For this “Z-Wave Door Lock Logging” device can you take a screenshot of the Status/Graphics page so that I can see what values map to what text strings? I’ll add support for this device in 1.0.0.

**Comment by danielbrunt57** [comment]
![image](https://user-images.githubusercontent.com/49846893/106501976-a27ebc80-6478-11eb-92de-7d23d34f7167.png)
![image](https://user-images.githubusercontent.com/49846893/106502032-b2969c00-6478-11eb-903a-48b2ce7ef9c3.png)

**Comment by marthoc** [comment]
So I've done some initial work on this but it is a bit more complicated than I initially thought - this is because the ASCII connection only sends the updated value of the device, not the updated status. This means that for this device (and other devices for which we need to obtain status), we will need to trigger a request to the JSON API to get the updated status value after the ASCII connection tells us there's a value update. I need to think about the best way to do that!

**Comment by danielbrunt57** [comment]
> the ASCII connection only sends the updated value of the device, not the updated status. 

Do you have that terminology reversed?  
I had a look at https://homeseer.com/support/homeseer/HS3/A2ZLink/default.htm and they talk about ASCII returning **status**...
![image](https://user-images.githubusercontent.com/49846893/106657447-e34a0480-6550-11eb-8a9d-a53c8bcffcea.png)
Looking at this device though, it would appear the ASCII call is getting **_status_** **23,dim**...
![image](https://user-images.githubusercontent.com/49846893/106656969-44bda380-6550-11eb-91a7-b11145ff649a.png)
but the pairs are listed as value:_status_ and its the associated "status" _string_ that needs to be retrieved.  Confusing as f$%^&^!!

**Comment by marthoc** [comment]
HS's terminology is not consistent across the JSON API, ASCII API, and the web user interface, and it is frustrating.

When connected to the ASCII interface, if a device changes, a message like this is sent over the connection:
`DC,576,1,0`
Which means "Device Change, ref 576, value was 1, now value is 0". Note that there's no status string that corresponds to that value sent, just the value itself for the ref.

Here's an example of what is returned over the JSON API:
```
{
    "Name": "HomeSeer Devices",
    "Version": "1.0",
    "Devices": [
        {
            "ref": 3398,
            "name": "Temperature",
            "location": "Z-Wave",
            "location2": "Node 122",
            "value": 82,
            "status": "82 F",
            "device_type_string": "Z-Wave Temperature",
            "last_change": "/Date(1410193983884)/",
            "relationship": 4,
            "hide_from_view": false,
            "associated_devices": [
                3397
            ],
            "device_type": {
                "Device_API": 16,
                "Device_API_Description": "Thermostat API",
                "Device_Type": 2,
                "Device_Type_Description": "Thermostat Temperature",
                "Device_SubType": 1,
                "Device_SubType_Description": "Temperature"
            },
            "device_image": ""
        },
        {
            "ref": 3570,
            "name": "Switch Binary",
            "location": "Z-Wave",
            "location2": "Node 124",
            "value": 255,
            "status": "On",
            "device_type_string": "Z-Wave Switch Binary",
            "last_change": "/Date(1410196540597)/",
            "relationship": 4,
            "hide_from_view": false,
            "associated_devices": [
                3566
            ],
            "device_type": {
                "Device_API": 4,
                "Device_API_Description": "Plug-In API",
                "Device_Type": 0,
                "Device_Type_Description": "Plug-In Type 0",
                "Device_SubType": 37,
                "Device_SubType_Description": ""
            },
            "device_image": ""
        }
    ]
}
```
So I think you can see it's the status string that we need to retrieve, and we can only do that by getting notification of a change from the ASCII API, then querying the JSON API. I think I've got it figured out and should have some code to test shortly.

**Comment by danielbrunt57** [comment]
Ok!
Question though...after getting `DC,576,1,0`, what would the ASCII command `gs,[576]` return?  The simple status? i.e. for my log: `23,dim`?

**Comment by marthoc** [comment]
Great question, and I have to say I don't know the answer.

**Comment by danielbrunt57** [comment]
Here's your answer!

![image](https://user-images.githubusercontent.com/49846893/106660100-7173ba00-6554-11eb-9b05-8e09ec8bbf7f.png)

**Comment by marthoc** [comment]
That's useful to know, thanks. Unfortunately it still stands that we need to make an additional API call, whether over JSON or ASCII, to get that status string!

**Comment by danielbrunt57** [comment]
It looks like the ASCII call is simpler to decode!
This exercise though disclosed that I left a timer running needlessly cluttering things up!

**Comment by marthoc** [comment]
At least the JSON response is... json, which python has inbuilt support for... should have some code for you to test tonight.

**Comment by marthoc** [comment]
@danielbrunt57 Support for this sensor has now been added to the 1.0.0 branch! Sorry this took so long, but supporting this sensor actually required a more or less complete rewrite of how the integration was talking to HomeSeer. The side benefit is that I actually found a bunch of unrelated bugs and quirks while doing so and generally improved the integration quite a bit, so 1.0.0 should actually be a pretty solid release. Give it a try and let me know if door lock logging shows up!

**Comment by marthoc** [comment]
PS you won’t need to remove and readd the integration, just stop HA, git pull the new commits from the 1.0.0 branch, and restart.

**Comment by danielbrunt57** [comment]
Okay, I've updated but would should the Door Lock Logging feature's Device Type String be set to?

Z-Wave Barrier Operator (as Home Assistant cover)
Z-Wave Battery (as Home Assistant sensor)
Z-Wave Door Lock (as Home Assistant lock)
Z-Wave Sensor Binary (as Home Assistant binary sensor)
Z-Wave Sensor Multilevel (as Home Assistant sensor)
Z-Wave Switch (as Home Assistant switch)
Z-Wave Switch Binary (as Home Assistant switch)
Z-Wave Switch Multilevel (as Home Assistant light or cover)
Z-Wave Central Scene (as Home Assistant event - see below)
Z-Wave Temperature (as Home Assistant sensor)
Z-Wave Relative Humidity (as Home Assistant sensor)
Z-Wave Luminance (as Home Assistant sensor)
Z-Wave Fan State for HVAC (as Home Assistant sensor)
Z-Wave Operating State for HVAC (as Home Assistant sensor)

**Comment by marthoc** [comment]
It should be the original string - "Z-Wave Door Lock Logging"

**Comment by danielbrunt57** [comment]
Yes, I dug inside your code and found DEVICE_ZWAVE_DOOR_LOCK_LOGGING, put 2 and 2 together and set it back to `Z-Wave Door Lock Logging`.  HA is now restarting...

**Comment by danielbrunt57** [comment]
It's not appearing.  I restarted HA twice now to be sure and also double checked the code in custom_components.

![image](https://user-images.githubusercontent.com/49846893/107825572-303f8f00-6d38-11eb-9226-2430f211e024.png)

![image](https://user-images.githubusercontent.com/49846893/107825623-451c2280-6d38-11eb-97f3-d645f02061de.png)

![image](https://user-images.githubusercontent.com/49846893/107825675-6a109580-6d38-11eb-8308-5625d8bb5228.png)

**Comment by danielbrunt57** [comment]
Hmmm...
```
Logger: custom_components.homeseer
Source: custom_components/homeseer/__init__.py:88
Integration: HomeSeer (documentation, issues)
First occurred: 1:37:56 PM (1 occurrences)
Last logged: 1:37:56 PM

Could not connect to HomeSeer at 192.168.1.103, aborting entry setup.
```

**Comment by marthoc** [comment]
Check the states page (Developer Tools/States) - sometimes new entities don't show up under the integrations page for some reason.

**Comment by marthoc** [comment]
The error you posted is obviously more concerning.

**Comment by danielbrunt57** [comment]
I removed/re-added the integration and I now have...

![image](https://user-images.githubusercontent.com/49846893/107826769-4bab9980-6d3a-11eb-99cc-b6146e0d69f3.png)

**Comment by danielbrunt57** [comment]
That switch.switch is a Neo Electronics NAS-WR01ZE Power Plug.
Similarly to the door lock, it has features that report kWh, Watts, Volts and Amps.  
Device Type Strings for the features is `Z-Wave Electric Meter`.
The Power Management Notification feature is `Z-Wave Notification`.

![image](https://user-images.githubusercontent.com/49846893/107827582-e2c52100-6d3b-11eb-8188-e44b82cbe9b7.png)

This is just for when you have time to kill!

**Comment by marthoc** [comment]
I’m going to be adding Z-Wave Electric Meter next as I just got a switch that has those attributes also!

**Comment by danielbrunt57** [comment]
![image](https://user-images.githubusercontent.com/49846893/107835022-ea40f600-6d4c-11eb-95df-78b4a64e6e8a.png)

**Comment by danielbrunt57** [comment]
Um, I just noticed the error returned...
```
Logger: custom_components.homeseer
Source: custom_components/homeseer/__init__.py:88
Integration: HomeSeer (documentation, issues)
First occurred: 3:32:00 PM (1 occurrences)
Last logged: 3:32:00 PM

Could not connect to HomeSeer at 192.168.1.103, aborting entry setup.
```
I've been tweaking my customize.yaml (not releated to HS) and had to restart HA to implement the changes.

**Comment by marthoc** [comment]
The integration has a time-out value for loading... I’m going to boost that up, which should prevent that.

**Comment by danielbrunt57** [comment]
I already boosted it to 30, restarted HA and no error (& entities are available).

**Comment by danielbrunt57** [comment]
Here's my Dev Tools, template session to get my sensors set...
```
{{ states.sensor.front_door_lock_logging }}

{{ states.sensor.front_door_lock_logging.state }}

Message: {{ states('sensor.front_door_lock_logging').split(' on ')[0] }}
Date: {{ states('sensor.front_door_lock_logging').split(' on ')[1].split(' at ')[0] }}
Time: {{ states('sensor.front_door_lock_logging').split(' at ')[1].split('User=')[0] }}
User: {{ states('sensor.front_door_lock_logging').split('User=')[1] }}

{{ as_timestamp(states.sensor.front_door_lock_logging.attributes["last_change"]) | timestamp_custom("%A %b %d") }}
{{ as_timestamp(states.sensor.front_door_lock_logging.attributes["last_change"]) | timestamp_custom("%H:%M:%S") }}
```
Result:
```
<template TemplateState(<state sensor.front_door_lock_logging=Unlocked using Keypad Code  on 2/13/2021 at 12:59:40 AM User=May; ref=762, location2=Z-Wave, location=Front Door, device_type_string=Z-Wave Door Lock Logging, value=2.0, status=Unlocked using Keypad Code  on 2/13/2021 at 12:59:40 AM User=May, last_change=2021-02-12T16:57:39-08:00, friendly_name=Front Door Lock Logging, icon=mdi:lock-clock @ 2021-02-12T16:57:39.884681-08:00>)>

Unlocked using Keypad Code  on 2/13/2021 at 12:59:40 AM User=May

Message: Unlocked using Keypad Code 
Date: 2/13/2021
Time: 12:59:40 AM 
User: May

Friday Feb 12
16:57:39
```
HA Sensors:
```
      frontdoor_lock_log_message:
        friendly_name: "Message"
        value_template: '{{ states("sensor.front_door_lock_logging").split(" on ")[0] }}'

      frontdoor_lock_log_user:
        friendly_name: "User"
        value_template: '{{ states("sensor.front_door_lock_logging").split("User=")[1] }}'

      frontdoor_lock_log_date:
        friendly_name: "Date"
        value_template: '{{ as_timestamp(states.sensor.front_door_lock_logging.attributes["last_change"]) | timestamp_custom("%A %b %d") }}'
        
      frontdoor_lock_log_time:
        friendly_name: "Time"
        value_template: '{{ as_timestamp(states.sensor.front_door_lock_logging.attributes["last_change"]) | timestamp_custom("%H:%M:%S") }}'
```

![image](https://user-images.githubusercontent.com/49846893/107839408-81637900-6d60-11eb-9468-52df1df47449.png)

![image](https://user-images.githubusercontent.com/49846893/107839431-ab1ca000-6d60-11eb-9bd5-ec8d04538135.png)

**Comment by marthoc** [comment]
Looks great! A nice side effect of supporting these status sensors is that I could also bring in the last_change attribute which I see you’re using!

**Comment by danielbrunt57** [comment]
Thanks!
I was trying to manipulate the date/time strings from the log record but after adding `{{ states.sensor.front_door_lock_logging }}` to my template session I noticed the last_change attribute which is already a timestamp and much easier to rework from UTC to local time!

**Comment by danielbrunt57** [comment]
![image](https://user-images.githubusercontent.com/49846893/109134107-8df5b300-770a-11eb-82c6-dbee1bb780fc.png)

**Comment by danielbrunt57** [comment]
The last_change attribute does not appear to be updating so it looks like I'll have to revert to extracting date & time from the status string...

```
ref: 762
location2: Z-Wave
location: Front Door
name: Front Door Lock Logging
device_type_string: Z-Wave Door Lock Logging
value: 14
status: 'Locked using Z-Wave  Today at 10:36:01 AM User Code=0'
last_change: '2021-03-23T03:28:17-07:00'
friendly_name: Front Door Lock Log
icon: 'mdi:lock-clock'
```

**Comment by marthoc** [comment]
Would be interesting to see the debug logs on this to determine why it’s not updating (is HomeSeer sending the wrong value? I would think so...)

**Comment by danielbrunt57** [comment]
![image](https://user-images.githubusercontent.com/49846893/112550047-fa041f00-8d7b-11eb-8eeb-996910ffe3b0.png)

**Comment by danielbrunt57** [comment]
![image](https://user-images.githubusercontent.com/49846893/112550191-3768ac80-8d7c-11eb-847c-8753f8a9ce6d.png)

**Comment by danielbrunt57** [comment]
Would that be why?

**Comment by marthoc** [comment]
That’s a yes I guess? Looks like the time corresponds to the last_change shown in HA?

**Comment by marthoc** [comment]
Oh yes - you should Untick that so that even the same value updates the last change.

**Comment by danielbrunt57** [comment]
Looks like it.  I unchecked it...
![image](https://user-images.githubusercontent.com/49846893/112550298-641cc400-8d7c-11eb-8dc0-ed2a09553349.png)

**Comment by danielbrunt57** [comment]
Thanks!
![Door Lock Log](https://user-images.githubusercontent.com/49846893/112550696-fde47100-8d7c-11eb-9ae0-ca6837746217.JPG)

**Comment by danielbrunt57** [comment]
What about this one?  Similar issue but the value did not change whereas the timestamp has...

![Dorr Lock Battery](https://user-images.githubusercontent.com/49846893/112551117-af83a200-8d7d-11eb-8a53-ee3d88eab2a5.JPG)

![Door Lock Battery - HS](https://user-images.githubusercontent.com/49846893/112551215-dc37b980-8d7d-11eb-8c7f-cff044827312.JPG)

**Comment by marthoc** [comment]
Not sure! Seems like a quirk of HS.
