### ISSUE TITLE
Add to HACS

### ISSUE THREAD

**Issue by jimcortez** [marthoc/homeseer#26]
Hey, this is a great idea. I am personally moving all my zwave devices to use Homeseer for more stability. Thank you for making this integration!

I have 1 request, add it to HACS https://hacs.xyz/docs/publish/start

This would make upgrading a bit easier to track and get notifications when things are ready. Looks like you have been doing a lot of work, so this would be helpful!

**Comment by marthoc** [comment]
@jimcortez I personally don’t use HACS but I appreciate that many users do... this is the second such request I’ve gotten re HACS so I think that’s the direction this is headed and I will probably change version 1.0.0 (few more features to add then will be ready to release) to HACS format.

**Comment by jimcortez** [comment]
Sounds great! If you need help testing before release, I am happy to help.

**Comment by danielbrunt57** [comment]
Fabulous!
![image](https://user-images.githubusercontent.com/49846893/109133887-4e2ecb80-770a-11eb-9f41-6d50688dea8a.png)
