### ISSUE TITLE
HA Devices in addition to Entities?

### ISSUE THREAD

**Issue by danielbrunt57** [marthoc/homeseer#32]
You may already be thinking about this but I'll post in case you're not...

Would it be possible for the integration to import the HS Root device into HA as a device that then has the other related entities associated with it?

![image](https://user-images.githubusercontent.com/49846893/107839686-672a9a80-6d62-11eb-95ec-4e1212f2ab14.png)

![image](https://user-images.githubusercontent.com/49846893/107839701-8c1f0d80-6d62-11eb-8e01-1ed73ebde923.png)

![image](https://user-images.githubusercontent.com/49846893/107839714-9fca7400-6d62-11eb-8d2a-f6155e886556.png)

![image](https://user-images.githubusercontent.com/49846893/107839728-bbce1580-6d62-11eb-8d2d-111fcbf19d46.png)

**Comment by marthoc** [comment]
It’s possible for sure. I hadn’t done it because unfortunately HS doesn’t expose a lot of useful data about the device over the JSON API, such as manufacturer, model #, serial number, etc. So all you’d really get is that device’s name.

**Comment by danielbrunt57** [comment]
I think it would be a nice improvement despite the lack of detailed info.

```
{
    "Name": "HomeSeer Devices",
    "Version": "1.0",
    "Devices": [
        {
            "ref": 3398,
            "name": "Temperature",
            "location": "Z-Wave",
            "location2": "Node 122",
            "value": 82,
            "status": "82 F",
            "device_type_string": "Z-Wave Temperature",
            "last_change": "/Date(1410193983884)/",
            "relationship": 4,
            "hide_from_view": false,
            "associated_devices": [
                3397
            ],
            "device_type": {
                "Device_API": 16,
                "Device_API_Description": "Thermostat API",
                "Device_Type": 2,
                "Device_Type_Description": "Thermostat Temperature",
                "Device_SubType": 1,
                "Device_SubType_Description": "Temperature"
            },
            "device_image": ""
        },
        {
            "ref": 3570,
            "name": "Switch Binary",
            "location": "Z-Wave",
            "location2": "Node 124",
            "value": 255,
            "status": "On",
            "device_type_string": "Z-Wave Switch Binary",
            "last_change": "/Date(1410196540597)/",
            "relationship": 4,
            "hide_from_view": false,
            "associated_devices": [
                3566
            ],
            "device_type": {
                "Device_API": 4,
                "Device_API_Description": "Plug-In API",
                "Device_Type": 0,
                "Device_Type_Description": "Plug-In Type 0",
                "Device_SubType": 37,
                "Device_SubType_Description": ""
            },
            "device_image": ""
        }
    ]
}
```

**Comment by danielbrunt57** [comment]
Thank you!!!
![image](https://user-images.githubusercontent.com/49846893/109133658-17f14c00-770a-11eb-95ed-a44c8faca91a.png)
