### ISSUE TITLE
Device String: Z-Wave Notification

### ISSUE THREAD

**Issue by gasm67** [marthoc/homeseer#35]
Hi, 

I've recently purchased a new Zwave Door Sensor, but instead of using the usual settings, it uses 22/23 for On/Off.  its set as  Device Type of  'Z-wave Notification', I did manage to fudge it using 'Zwave Temperature', but obviously that is not ideal.

Would it be possible to have a Notification, device type which reports back the value as is ?  Looking forward to the Electric meter values being passed through.

![Screenshot 2021-02-18 143518](https://user-images.githubusercontent.com/34502369/108391096-41d9d880-7209-11eb-9c8e-6d12b81840de.jpg)

![Screenshot 2021-02-18 143451](https://user-images.githubusercontent.com/34502369/108391627-cb89a600-7209-11eb-82d8-9404109873e7.jpg)

**Comment by marthoc** [comment]
This should probably appear in Home Assistant as a binary sensor - i.e. an "Open/Close" device - rather than as a sensor with values passed through. Agreed?

EDIT: I just took a look at my own HomeSeer instance and I've got a Z-Wave Notification device type for my door lock that reports a ton of different values. I think the way to handle this in the short term is to create this device as a sensor whose status is the string associated with the value - at least that way you'd get "Open" and "Closed" reported. Sound good?

**Comment by gasm67** [comment]
Yes, I would agree, that is what I would expect a window/door sensor to be added as - so the issue would probably be with what HS4 reads it as.
Do you know if it is possible to change the values in HS4, or is this an issue that should be raised with them ?

G




Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by marthoc** [comment]
I think that how the device gets imported into HomeSeer is partly based on the Z-Wave command classes it reports, which will be up to the manufacturer. I know that the Dome contact sensors I have are imported into HomeSeer with the type "Z-Wave Sensor Binary".

**Comment by gasm67** [comment]
Thought that, it was a new device I purchased from Amazon.  Decent quality to some of them I have purchased previously.

As, I said, I did manage to use it under temperature, and get the two values passed through.  At least it worked (in a fashion).

Btw, I do appreciate the work you do.

TechniSat Z-Wave Plus Door Contact 2 (Smart Home Sensor for displaying the closing status of windows and doors, House Control via app, Wireless Magnetic Contacts): Amazon.co.uk: DIY & Tools<https://www.amazon.co.uk/gp/product/B07SZV7SJM/ref=ppx_yo_dt_b_asin_title_o02_s00?ie=UTF8&psc=1>

When reading your GitHub, I saw something about reporting the electric power values, is that working yet, as I don’t see anything being passed yet ?

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by marthoc** [comment]
> When reading your GitHub, I saw something about reporting the electric power values, is that working yet, as I don’t see anything being passed yet ?

Support for the electric meter devices is added in 1.0.0, which I am hoping to release tomorrow. Rushing to get some final features in and Z-Wave Notification support will be one of them!

**Comment by gasm67** [comment]
Excellent news Mark, I’ll give it a test once its up and running.

I’ll give my feedback.

Rgds,
G

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10
