### ISSUE TITLE
unable to install

### ISSUE THREAD

**Issue by ddesme01** [marthoc/homeseer#44]
After following the directions, the homeseer integration does not show up in configuration ->integrations ->add integration

**Comment by marthoc** [comment]
Which directions? For manual install?

The directory structure should be:

config/custom_components/homeseer/__init__.py
config/custom_components/homeseer/binary_sensor.py
etc.

This means that you will need to download and extract the release (into a tmp dir); cd into the custom_components directory, and then mv the homeseer directory into your installation.

If the custom integration is in the proper place, there should be a warning in the logs that you are using a custom component for homeseer. If you don't see that log message, the integration isn't in the correct place.

**Comment by jradwan** [comment]
I'm having a similar problem. Followed the instructions for HACS install, so the repo shows up under HACS > Integrations, but it doesn't show up under Configuration > Integrations > Add so I can't figure out where to add the configuration info in the install instructions (IP address of HomeSeer, etc.).

**Comment by jradwan** [comment]
> I'm having a similar problem. Followed the instructions for HACS install, so the repo shows up under HACS > Integrations, but it doesn't show up under Configuration > Integrations > Add so I can't figure out where to add the configuration info in the install instructions (IP address of HomeSeer, etc.).

Nevermind, looks like I just had to wait. Today I was able to find Homeseer in the add integrations dialog and proceed with the configuration.

**Comment by marthoc** [comment]
Sometimes it takes a couple restarts of HA to have a custom integration show up in the Integrations menu, I don’t know why.
