### ISSUE TITLE
Insteon Devices in HomeSeer

### ISSUE THREAD

**Issue by Airey001** [marthoc/homeseer#49]
So I installed this as a way to merge the gap between Home Assistant and HomeSeer.   I only use HomeSeer for the lack of insteon product supportly current in Home Assistant.   My End all goal is to get everything in HomeAssistant some how and I believe better insteon support is years away from where it is in Home Seer with Marks plugin.

Anyway I added your integration to HA and configured it to only pull in my Insteon Devices from HomeSeer.  It worked and pulled them in but i am finding some issue

First is Garage Doors.  Insteon uses a I/O sensor/relay device with a wired magnetic sensor and a on/off relay for telling it to open and closed.   This device added in but instead of having the input sensor and output relay it is getting 2 entity for the output relay.
![HA-GD](https://user-images.githubusercontent.com/32739694/114935662-7339e380-9e09-11eb-8529-e37b1cd39123.PNG)
![HS-GD](https://user-images.githubusercontent.com/32739694/114935664-7339e380-9e09-11eb-8377-6ee22ba81238.PNG)

The Input sensor which is not and entity is what tell HomeSeer the door is opened closed.  

Next issue i noticed is my Insteon KPL which are wall switched which can have 6 or 8 buttons to confuigure.  Newer version of the PKL will allow you to detach the load from the switch buttons so you can't control the load from the switch.  I am using that option but it appears when the intigration added the PKL it didn't add an entitiy for the first button instead it created the device as button a so i have no way to control it.
![HA-SG](https://user-images.githubusercontent.com/32739694/114936423-6c5fa080-9e0a-11eb-9296-294796ba6e55.PNG)
![HS-SG](https://user-images.githubusercontent.com/32739694/114936425-6c5fa080-9e0a-11eb-9840-01e78267e340.PNG)

This is only first round of testing on a dev HA.  Want to get this right before i add to prod but this plugin is my key to being able to use the HA system as the main controler to use with its great UI and Cards.

**Comment by Airey001** [comment]
So I reverted down to HS3 from HS4 and the garge door issue is in a workign state it only gives me an on off option but that works off shuts it on openes it.

The KPL still don't show up correctly.

**Comment by marthoc** [comment]
@Airey001 I know why both issues are happening. 

With regard to the Garage Door opener, the creator of the Insteon PI in HS has decided to separate the sensor and the switch into two different devices - the Z-Wave PI combines them so that one device has both the Open/Close control and also the status. You can combine them into one entity in HA using a template cover: https://www.home-assistant.io/integrations/cover.template/ .

As for the keypad, again the creator of the Insteon PI has decided to model this as separate devices for each button. I'm willing to bet that the first switch is marked as the "root" device. In the Z-Wave PI, root devices are purely descriptive and have no controls or status. I could fix this by having this integration not ignore root devices as it does currently (currently uses them only to create a master device to group all of the devices).

**Comment by Airey001** [comment]
I was about to try the Template Cover when I realized the sensor and switch in HA are not getting updated when the garage is up and down to match HomeSeer.  Like I just came up and opened my 2nd garage bay and noticed that it was suck as saying it was opened from when i left this am.  It never registered the close when i left and the reopen and close when i came home but Homeseer has those recorded in the logs.  Is the a pooling time?  

Is there a way if i can see if a device is set to root in homeseer? for the KPL's

**Comment by Airey001** [comment]
I found how to see parent child in Homeseer.  Yes the first switch is marked 'Root' all others are child.

**Comment by Airey001** [comment]
I just found antother issue Device Bleeding where buttons from one device have blead to another:

![Device Bleeding](https://user-images.githubusercontent.com/32739694/116000204-387c3c00-a5bd-11eb-8fd0-fccf4a22c87f.PNG)


So this device The Office Overhead should on/off however it some how got several other switchs from one of the KPLS added to it.

In fact I am seeing this all over I have several devices with switches from others.

**Comment by marthoc** [comment]
Ok. To begin to debug the issues, I will need you to turn on debug logging in Home Assistant as described in the README of this repo. Restart HA with debug logging turned on, then ideally you could toggle your garage door manually so I can check the logs to see if anything has come over the ASCII connection. With the debug log I will be ablee to trace some of these issues. The log will not have any passwords to redact.

**Comment by Airey001** [comment]
So i have re-installed several times with mixed results but during that time one of my garage door openers broke.  So when i was at the store i found a new craftsman garage door with MyQ built in and then on the Clarence rack they had 2 MyQ hubs to turn old garge doors into smart ones for only 10 bucks a peice.  So i moved them all to MyQ intaration and they work fine.   As per home seer i will be giting rid of it fully and moving my insteion items items to the HA intigration which is getting a major upgrade soon.  There is a pull request in to give it a UI and be able to program my insteion devices from HA so i won't be using your intigration.  I will say it is nice and works really good and fast.
