### ISSUE TITLE
Need Root Device Created as Entity for Insteon Hidden Door Sensor

### ISSUE THREAD

**Issue by Sinandgrin** [marthoc/homeseer#54]
I’m new to HA and slowly migrating devices around the house into HA and have a lot of Insteon equipment. I was very happy to be able to get the HomeSeer Custom Integration for Home Assistant working for the most part. One issue I have is with 2 Insteon Hidden Door Sensors where I am missing the Root/Parent reference device (REF# 904 in the image below). The Integration was able to pull in all the other child devices though but as you can see, the one I really need is the open/close status of the Root device.

Pulling the logs it looks like this is purposely not created.

2021-07-25 10:45:08 DEBUG (MainThread) [custom_components.homeseer.homeseer] Device ref 904 is a root device, not creating an entity for this device

Is there a way I can manually create an Entity for this Device in HA or that you can update the integration to accommodate this need?

![image](https://user-images.githubusercontent.com/5924175/126905206-36d2ab07-ce52-433f-83be-e7dda35db998.png)

**Comment by marthoc** [comment]
This is a quirk of certain HomeSeer plugins. As far as I know, root devices are not supposed to have their own features and the HS native root devices (e.g. for Z-Wave) don't. I will take a look at supporting this. I think that supporting it doesn't really change much except that an additional (useless) entity will be created for Z-Wave devices. Stay tuned.

**Comment by Sinandgrin** [comment]
Thanks @marthoc, eager to see if you make any progress here.

**Comment by Sinandgrin** [comment]
Sweet thanks @marthoc. Going to update and test this out later this weekend.

**Comment by marthoc** [comment]
Working on my end for Z-Wave anyway, just creates another entity attached to the device.
