### ISSUE TITLE
HomeSeer doesn't show up in the configuration -> Integration

### ISSUE THREAD

**Issue by Srki82** [marthoc/homeseer#60]
Hi,
I have tried to install this custom component without success. I can install it in HACS and it showed up properly in HACS but when I try to search for it in the configuration -> Integration it cannot be found so I cannot set it up. Does anyone know how to fix this?

**Comment by kmitch95120** [comment]
Did you restart HA after installing it in HACS? That's required before it will show up in Configuration->Integrations.

**Comment by Srki82** [comment]
Several time...it didn't work. I also restarted my VM and after second restart it showed up... setting it up now
