### ISSUE TITLE
Scenes from Homeseer Switches

### ISSUE THREAD

**Issue by bds42** [marthoc/homeseer#61]
Is it possible to get the special button presses from the HomeSeer dimmer switches such as the HS-WD200?  
Would like to be able to run an automation if I double tap the off button, etc...

**Comment by kmitch95120** [comment]
This should already work.  These are treated as a Central Scene Controller so they fire events in Home Assistant. The one "glitch" I've run into is the fact that the HS ASCII interface only sends notification of a Central Scene when the Scene actually changes.  In other words, once.  To get around this you'll need to set up an HS event that "resets" the Central Scene back to "0" when it's set to something greater than "0".  

Let me know if you need a hand with the setup. 
Ken

**Comment by marthoc** [comment]
Yes @kmitch95120 is correct on this - you can see an example of the HA event that is fired for a Central Scene device in the README. Ken is also correct that a limitation of the HS API is that this only gets sent when a different event from the last is sent. Resetting the status back via an HS event is a good workaround.
