### ISSUE TITLE
how to change wrong imported devices (a switch is a sensor in homeassistant instead of a switch)?

### ISSUE THREAD

**Issue by malosaa** [marthoc/homeseer#62]
Like i have for example a rfxcom device,
it shows up as a normal sensor, but it needs to be a switch..

how can i change it in homeassistant ?

**Comment by marthoc** [comment]
It shows up as a sensor in Home Assistant because the device in HomeSeer does not have control pairs for on and off. Can you show me a screenshot of the "Status Graphics" page for the device that should be switch?

**Comment by malosaa** [comment]
@marthoc 

its from the plugwise plugin from Stefxx
![image](https://user-images.githubusercontent.com/13116501/133459669-a1285a39-943a-4912-a11f-c1ec27f6b610.png)

**Comment by marthoc** [comment]
That is interesting. May be an actual bug. Can you turn on debug logging (instructions in the README) and then send me the log that results after you start HA? It will give me the API responses and I can see what's going wrong.

**Comment by malosaa** [comment]
@marthoc 

while i was trying the whole day, i did remove plugin and re-add it.
now i find the relay acting as a switch.

I don't know what the issue was, but i did update version aswell.

regards

**Comment by marthoc** [comment]
Yea it could be the version update, support for a wider range of devices was recently added.

**Comment by malosaa** [comment]
@marthoc 

actually i have a question about a rfxcom device, with on/of and slider.

is it possible to import with slider and on/off ?
![image](https://user-images.githubusercontent.com/13116501/133638930-303c5d95-fea2-48ac-b997-0c5392d1527b.png)
 
shows as sensor in HASS
![image](https://user-images.githubusercontent.com/13116501/133639128-701cd0b6-3bcf-437d-877a-441679509feb.png)

**Comment by marthoc** [comment]
Yes. This device is not importing correctly because it has two "Off" control uses and no "On" control use. You will need to change the "On" status control use from "Off" to "On", and change the control use for the range 1-99 to "Dim". If you restart HA, the device will then be imported into HA as a light with a dim slider.

**Comment by malosaa** [comment]
@marthoc 

thanks it shows up.
u maybe know how i can change it to a ventilation sensor, or is this not possible ?
