### ISSUE TITLE
Binary Switches

### ISSUE THREAD

**Issue by vansy02** [marthoc/homeseer#63]
I have an issue with my binary switches (simple on off switches, no dimmer) in that I'm able to turn them off in Home Assistant, but the option to turn them on never populates. I turn the switch off and it doesn't change to the ability to turn it on.  It tracks the status correctly in identifying on (but have to do manually) and off but can't actually turn on.

**Comment by marthoc** [comment]
You will need to enable debug logging per the instructions in the README. After you've done that, start HA and toggle the switch, etc. so that I can see what API responses are being returned.

**Comment by vansy02** [comment]
Thanks! I'll do that tonight and upload.

**Comment by vansy02** [comment]
Went through the process again, just defaulted to all Zwave devices and everything seem to be working now.
